import 'dart:async';
import 'dart:io';
import 'package:path/path.dart' as p;

/// Risk level for an approval request.
enum ApprovalLevel {
  normal,
  red,
}

/// Status of the approval decision.
enum ApprovalStatus {
  approved,
  denied,
  timeout,
  unavailable,
}

/// A request to approve command execution.
/// Contains ONLY information generated by the local validator, never model-supplied text.
class ApprovalRequest {
  final String command;
  final String cwd;
  final ApprovalLevel level;
  final String reason;

  const ApprovalRequest({
    required this.command,
    required this.cwd,
    required this.level,
    required this.reason,
  });
}

/// Record of an individual confirmation stage for RED approvals.
class ApprovalStage {
  final int stage;
  final ApprovalStatus status;
  final int? latencyMs;
  final String? message;

  const ApprovalStage({
    required this.stage,
    required this.status,
    this.latencyMs,
    this.message,
  });

  Map<String, dynamic> toJson() => {
    'stage': stage,
    'status': status.name,
    if (latencyMs != null) 'latencyMs': latencyMs,
    if (message != null) 'message': message,
  };
}

/// Result of an approval request.
class ApprovalResult {
  final ApprovalStatus status;
  final String? message;
  final int? latencyMs;
  final String? providerName;
  final List<ApprovalStage>? stages;
  final bool? fastApproval;

  const ApprovalResult({
    required this.status,
    this.message,
    this.latencyMs,
    this.providerName,
    this.stages,
    this.fastApproval,
  });

  const ApprovalResult.approved([
    String? message,
    int? latencyMs,
    String? providerName,
    List<ApprovalStage>? stages,
    bool? fastApproval,
  ])  : status = ApprovalStatus.approved,
        message = message,
        latencyMs = latencyMs,
        providerName = providerName,
        stages = stages,
        fastApproval = fastApproval;

  const ApprovalResult.denied([
    String? message,
    int? latencyMs,
    String? providerName,
    List<ApprovalStage>? stages,
  ])  : status = ApprovalStatus.denied,
        message = message,
        latencyMs = latencyMs,
        providerName = providerName,
        stages = stages,
        fastApproval = null;

  const ApprovalResult.timeout([
    String? message,
    int? latencyMs,
    String? providerName,
    List<ApprovalStage>? stages,
  ])  : status = ApprovalStatus.timeout,
        message = message,
        latencyMs = latencyMs,
        providerName = providerName,
        stages = stages,
        fastApproval = null;

  const ApprovalResult.unavailable([
    String? message,
    String? providerName,
  ])  : status = ApprovalStatus.unavailable,
        message = message,
        latencyMs = null,
        providerName = providerName,
        stages = null,
        fastApproval = null;

  bool get isApproved => status == ApprovalStatus.approved;
}

/// Interface for requesting local approval for commands requiring user confirmation.
abstract interface class ApprovalProvider {
  String get name;
  Future<ApprovalResult> request(ApprovalRequest request);
}

typedef ProcessStarter = Future<Process> Function(
  String executable,
  List<String> arguments, {
  Map<String, String>? environment,
});

/// Discovers GUI environment variables (Wayland/X11/DBus) for desktop dialogs.
/// Checks inherited environment first, then active user session sockets under /run/user/<uid>/ only,
/// then X11 fallback sockets (/tmp/.X11-unix/X0, etc.).
/// Enforces that discovered sockets MUST:
/// - Be strictly confined to /run/user/<uid>/ or /tmp/.X11-unix/
/// - Exist and NOT be a symbolic link
/// - Be owned by the current user's UID (checked via file stat owner)
/// Emits a single diagnostic line to stderr specifying which source was used,
/// without printing any secrets.
class DisplayDiscovery {
  final Map<String, String> environment;
  final String? runUserBaseDir;
  final String? x11UnixBaseDir;
  final String? currentUid;
  final void Function(String line)? onLogStderr;
  final Object? Function(String path)? fileOwnerResolver;
  bool _hasLogged = false;

  DisplayDiscovery({
    Map<String, String>? environment,
    this.runUserBaseDir,
    this.x11UnixBaseDir,
    this.currentUid,
    this.onLogStderr,
    this.fileOwnerResolver,
  }) : environment = environment ?? Platform.environment;

  /// Retrieves the owner UID of a file/socket using `stat -c %u` (or injected resolver).
  String? _getFileOwnerUid(String path) {
    if (fileOwnerResolver != null) {
      return fileOwnerResolver!(path)?.toString();
    }
    try {
      final res = Process.runSync('stat', ['-c', '%u', path]);
      if (res.exitCode == 0) {
        final out = res.stdout.toString().trim();
        if (out.isNotEmpty) return out;
      }
    } catch (_) {}
    return null;
  }

  /// Verifies that a discovered display socket:
  /// 1. Is located strictly inside /run/user/<uid>/ or /tmp/.X11-unix/ (never outside)
  /// 2. Exists and is NOT a symlink
  /// 3. Is owned by the current user's UID (checked via file stat owner)
  bool _isValidDisplaySocket(String socketPath, String expectedUid) {
    final normalized = p.normalize(socketPath);
    final allowedRunUser = p.normalize(
      runUserBaseDir != null ? '$runUserBaseDir/$expectedUid' : '/run/user/$expectedUid',
    );
    final allowedX11 = p.normalize(x11UnixBaseDir ?? '/tmp/.X11-unix');

    // Strict boundary enforcement: socket MUST be under /run/user/<uid>/ or /tmp/.X11-unix/
    final isUnderRunUser = normalized.startsWith('$allowedRunUser/') || normalized == allowedRunUser;
    final isUnderX11 = normalized.startsWith('$allowedX11/') || normalized == allowedX11;
    if (!isUnderRunUser && !isUnderX11) {
      return false;
    }

    // Must exist
    final entityType = FileSystemEntity.typeSync(normalized, followLinks: false);
    if (entityType == FileSystemEntityType.notFound) {
      return false;
    }

    // Must NOT be a symlink
    if (entityType == FileSystemEntityType.link || FileSystemEntity.isLinkSync(normalized)) {
      return false;
    }

    // Must be owned by current user's UID
    final ownerUid = _getFileOwnerUid(normalized);
    if (ownerUid == null || ownerUid.trim() != expectedUid.trim()) {
      return false;
    }

    return true;
  }

  /// Validates that a display socket candidate satisfies all security rules:
  /// 1. Strictly inside /run/user/<uid>/ or /tmp/.X11-unix/
  /// 2. Exists and is NOT a symbolic link
  /// 3. Owned by the current user's UID
  bool isValidDisplaySocket(String socketPath, String expectedUid) =>
      _isValidDisplaySocket(socketPath, expectedUid);

  Map<String, String> discover() {
    final env = <String, String>{};
    for (final key in [
      'DISPLAY',
      'WAYLAND_DISPLAY',
      'XDG_RUNTIME_DIR',
      'DBUS_SESSION_BUS_ADDRESS',
      'HOME',
      'PATH',
    ]) {
      final val = environment[key];
      if (val != null && val.trim().isNotEmpty) {
        env[key] = val.trim();
      }
    }

    String? resolvedSource;

    // 1. Inherited environment check
    if (env.containsKey('WAYLAND_DISPLAY')) {
      resolvedSource = 'inherited WAYLAND_DISPLAY';
    } else if (env.containsKey('DISPLAY')) {
      resolvedSource = 'inherited DISPLAY';
    }

    // 2. Discover session sockets strictly under /run/user/<uid>/ only
    if (Platform.isLinux || runUserBaseDir != null || x11UnixBaseDir != null) {
      String? uid = currentUid;
      if (uid == null) {
        try {
          final uidResult = Process.runSync('id', ['-u']);
          if (uidResult.exitCode == 0) {
            uid = uidResult.stdout.toString().trim();
          }
        } catch (_) {}
      }

      if (!env.containsKey('XDG_RUNTIME_DIR') && uid != null && uid.isNotEmpty) {
        final baseDir = runUserBaseDir ?? '/run/user';
        final candidate = '$baseDir/$uid';
        if (Directory(candidate).existsSync()) {
          env['XDG_RUNTIME_DIR'] = candidate;
        }
      }

      final runtimeDir = env['XDG_RUNTIME_DIR'];

      if (resolvedSource == null && !env.containsKey('WAYLAND_DISPLAY') && runtimeDir != null && uid != null) {
        for (final name in ['wayland-0', 'wayland-1', 'wayland-2']) {
          final candidatePath = '$runtimeDir/$name';
          if (_isValidDisplaySocket(candidatePath, uid)) {
            env['WAYLAND_DISPLAY'] = name;
            resolvedSource = 'session socket $candidatePath';
            break;
          }
        }
      }

      // 3. X11 fallback discovery: strictly under /run/user/<uid>/ or /tmp/.X11-unix/
      if (resolvedSource == null && !env.containsKey('DISPLAY') && uid != null) {
        // First check under runtime directory
        if (runtimeDir != null) {
          for (final display in [':0', ':1']) {
            final candidatePath = '$runtimeDir/X11-unix/X${display.substring(1)}';
            if (_isValidDisplaySocket(candidatePath, uid)) {
              env['DISPLAY'] = display;
              resolvedSource = 'session socket $candidatePath';
              break;
            }
          }
        }

        // Then check under X11 unix socket directory (/tmp/.X11-unix/)
        if (resolvedSource == null) {
          final x11Base = x11UnixBaseDir ?? '/tmp/.X11-unix';
          for (final display in [':0', ':1']) {
            final candidatePath = '$x11Base/X${display.substring(1)}';
            if (_isValidDisplaySocket(candidatePath, uid)) {
              env['DISPLAY'] = display;
              resolvedSource = 'X11 fallback $candidatePath';
              break;
            }
          }
        }
      }

      // 4. Resolve DBUS_SESSION_BUS_ADDRESS if missing
      if (!env.containsKey('DBUS_SESSION_BUS_ADDRESS') && runtimeDir != null && uid != null) {
        final busPath = '$runtimeDir/bus';
        if (_isValidDisplaySocket(busPath, uid)) {
          env['DBUS_SESSION_BUS_ADDRESS'] = 'unix:path=$busPath';
        }
      }
    }

    if (resolvedSource != null && !_hasLogged) {
      _hasLogged = true;
      final logFn = onLogStderr ?? stderr.writeln;
      logFn('ubuntu-shell-mcp: GUI display resolved via $resolvedSource');
    }

    return env;
  }
}

/// Desktop GUI implementation of [ApprovalProvider] using `zenity`.
/// Invoked with `Process.start` and an argument list (no shell).
class ZenityApprovalProvider implements ApprovalProvider {
  @override
  String get name => 'zenity';

  final Duration timeout;
  final Map<String, String>? environmentOverride;
  final String zenityPath;
  final ProcessStarter? processStarter;
  final DisplayDiscovery _discovery;

  Future<void> _dialogQueue = Future.value();

  ZenityApprovalProvider({
    this.timeout = const Duration(seconds: 60),
    this.environmentOverride,
    this.zenityPath = 'zenity',
    this.processStarter,
    DisplayDiscovery? discovery,
  }) : _discovery = discovery ?? DisplayDiscovery();

  /// Extracts GUI environment variables, falling back to detecting active user session sockets
  /// under /run/user/<uid>/ and X11 sockets if stripped by the launcher.
  Map<String, String> buildGuiEnvironment() {
    if (environmentOverride != null) {
      return environmentOverride!;
    }
    return _discovery.discover();
  }

  /// Checks if zenity is available on the host system.
  bool _isZenityAvailable(Map<String, String> env) {
    if (processStarter != null) return true;
    if (File('/usr/bin/zenity').existsSync()) return true;
    final pathVar = env['PATH'] ?? Platform.environment['PATH'] ?? '/usr/local/bin:/usr/bin:/bin';
    for (final dir in pathVar.split(':')) {
      if (dir.isNotEmpty && File('$dir/$zenityPath').existsSync()) {
        return true;
      }
    }
    return false;
  }

  @override
  Future<ApprovalResult> request(ApprovalRequest request) {
    final completer = Completer<ApprovalResult>();
    _dialogQueue = _dialogQueue.catchError((_) {}).then((_) async {
      try {
        final result = await _processRequest(request);
        completer.complete(result);
      } catch (e, st) {
        completer.completeError(e, st);
      }
    });
    return completer.future;
  }

  Future<ApprovalResult> _processRequest(ApprovalRequest request) async {
    final env = buildGuiEnvironment();

    // Check display environment
    final hasDisplay = env.containsKey('DISPLAY') || env.containsKey('WAYLAND_DISPLAY');
    if (!hasDisplay) {
      return const ApprovalResult.unavailable(
        'neither DISPLAY nor WAYLAND_DISPLAY is set in server environment',
        'zenity',
      );
    }

    // Check zenity executable
    if (!_isZenityAvailable(env)) {
      return const ApprovalResult.unavailable(
        'zenity is not installed on this system',
        'zenity',
      );
    }

    if (request.level == ApprovalLevel.normal) {
      final sw = Stopwatch()..start();
      final dialogResult = await _showDialog(
        args: _buildNormalArgs(request),
        env: env,
      );
      sw.stop();
      final latency = sw.elapsedMilliseconds;
      return ApprovalResult(
        status: dialogResult.status,
        message: dialogResult.message,
        latencyMs: latency,
        providerName: name,
        fastApproval: latency < 800,
      );
    } else {
      // Red level: requires two confirmation dialogs
      final stages = <ApprovalStage>[];
      final sw1 = Stopwatch()..start();
      final firstResult = await _showDialog(
        args: _buildRedFirstArgs(request),
        env: env,
      );
      sw1.stop();
      final latency1 = sw1.elapsedMilliseconds;
      stages.add(ApprovalStage(
        stage: 1,
        status: firstResult.status,
        latencyMs: latency1,
        message: firstResult.message,
      ));

      if (!firstResult.isApproved) {
        return ApprovalResult(
          status: firstResult.status,
          message: firstResult.message,
          latencyMs: latency1,
          providerName: name,
          stages: stages,
          fastApproval: latency1 < 800,
        );
      }

      // Second confirmation dialog
      final sw2 = Stopwatch()..start();
      final secondResult = await _showDialog(
        args: _buildRedSecondArgs(request),
        env: env,
      );
      sw2.stop();
      final latency2 = sw2.elapsedMilliseconds;
      stages.add(ApprovalStage(
        stage: 2,
        status: secondResult.status,
        latencyMs: latency2,
        message: secondResult.message,
      ));

      final totalLatency = latency1 + latency2;
      return ApprovalResult(
        status: secondResult.status,
        message: secondResult.message,
        latencyMs: totalLatency,
        providerName: name,
        stages: stages,
        fastApproval: totalLatency < 800,
      );
    }
  }

  List<String> _buildNormalArgs(ApprovalRequest req) {
    final text = 'Command to execute:\n'
        '--------------------------------------------------\n'
        '${req.command}\n'
        '--------------------------------------------------\n'
        'Working Directory: ${req.cwd}\n'
        'Reason: ${req.reason}';

    return [
      '--question',
      '--title=Allow this command?',
      '--text=$text',
      '--no-markup',
      '--ok-label=Allow',
      '--cancel-label=Deny',
      '--icon-name=dialog-question',
      '--timeout=${timeout.inSeconds}',
      '--width=600',
    ];
  }

  List<String> _buildRedFirstArgs(ApprovalRequest req) {
    final text = 'WARNING: DANGEROUS / SENSITIVE COMMAND REQUESTED\n\n'
        'Command to execute:\n'
        '--------------------------------------------------\n'
        '${req.command}\n'
        '--------------------------------------------------\n'
        'Working Directory: ${req.cwd}\n'
        'Reason: ${req.reason}';

    return [
      '--question',
      '--title=DANGEROUS: review carefully',
      '--text=$text',
      '--no-markup',
      '--ok-label=Allow',
      '--cancel-label=Deny',
      '--icon-name=dialog-warning',
      '--timeout=${timeout.inSeconds}',
      '--width=600',
    ];
  }

  List<String> _buildRedSecondArgs(ApprovalRequest req) {
    final text = 'FINAL CONFIRMATION REQUIRED:\n\n'
        'Are you ABSOLUTELY sure you want to execute this dangerous command?\n'
        'This action cannot be undone.\n\n'
        'Command:\n'
        '--------------------------------------------------\n'
        '${req.command}\n'
        '--------------------------------------------------';

    return [
      '--question',
      '--title=DANGEROUS: Final Confirmation',
      '--text=$text',
      '--no-markup',
      '--ok-label=Yes, Execute Dangerous Command',
      '--cancel-label=Cancel / Deny',
      '--icon-name=dialog-warning',
      '--default-cancel',
      '--timeout=${timeout.inSeconds}',
      '--width=600',
    ];
  }

  Future<ApprovalResult> _showDialog({
    required List<String> args,
    required Map<String, String> env,
  }) async {
    Process process;
    try {
      if (processStarter != null) {
        process = await processStarter!(
          zenityPath,
          args,
          environment: env,
        );
      } else {
        process = await Process.start(
          zenityPath,
          args,
          environment: env,
        );
      }
    } catch (e) {
      return ApprovalResult.unavailable('Failed to spawn zenity: $e');
    }

    try {
      final exitCode = await process.exitCode.timeout(timeout);
      switch (exitCode) {
        case 0:
          return const ApprovalResult.approved('Approved by user');
        case 1:
          return const ApprovalResult.denied('Denied by user');
        case 5:
          return const ApprovalResult.timeout('Dialog timed out after 60 seconds');
        default:
          return ApprovalResult.denied('Dialog closed with code $exitCode');
      }
    } on TimeoutException {
      try {
        process.kill(ProcessSignal.sigterm);
      } catch (_) {}
      return const ApprovalResult.timeout('Dialog timed out after 60 seconds');
    } catch (e) {
      try {
        process.kill(ProcessSignal.sigterm);
      } catch (_) {}
      return ApprovalResult.denied('Dialog error: $e');
    }
  }
}

/// In-memory fake approval provider for testing without GUI popups.
class FakeApprovalProvider implements ApprovalProvider {
  @override
  String get name => 'fake';

  final List<ApprovalRequest> requestsReceived = [];
  final ApprovalResult Function(ApprovalRequest req)? onHandleRequest;
  ApprovalStatus defaultStatus;
  int activeRequestsCount = 0;
  int maxConcurrentRequests = 0;

  FakeApprovalProvider({
    this.defaultStatus = ApprovalStatus.denied,
    this.onHandleRequest,
  });

  @override
  Future<ApprovalResult> request(ApprovalRequest request) async {
    requestsReceived.add(request);
    activeRequestsCount++;
    if (activeRequestsCount > maxConcurrentRequests) {
      maxConcurrentRequests = activeRequestsCount;
    }
    // Yield to event loop to simulate realistic async UI
    await Future.delayed(const Duration(milliseconds: 5));
    activeRequestsCount--;

    if (onHandleRequest != null) {
      final res = onHandleRequest!(request);
      final latency = res.latencyMs ?? 5;
      final stages = res.stages ??
          (request.level == ApprovalLevel.red
              ? [
                  ApprovalStage(stage: 1, status: res.status, latencyMs: 3),
                  if (res.isApproved)
                    ApprovalStage(stage: 2, status: res.status, latencyMs: 2),
                ]
              : null);
      return ApprovalResult(
        status: res.status,
        message: res.message,
        latencyMs: latency,
        providerName: res.providerName ?? name,
        stages: stages,
        fastApproval: res.fastApproval ?? (latency < 800),
      );
    }

    final totalLatency = request.level == ApprovalLevel.red && defaultStatus == ApprovalStatus.approved ? 10 : 5;
    final stages = request.level == ApprovalLevel.red
        ? [
            ApprovalStage(stage: 1, status: defaultStatus, latencyMs: 5),
            if (defaultStatus == ApprovalStatus.approved)
              ApprovalStage(stage: 2, status: defaultStatus, latencyMs: 5),
          ]
        : null;

    switch (defaultStatus) {
      case ApprovalStatus.approved:
        return ApprovalResult.approved(
          'Approved by test user',
          totalLatency,
          name,
          stages,
          true,
        );
      case ApprovalStatus.denied:
        return ApprovalResult.denied(
          'Denied by test user',
          totalLatency,
          name,
          stages,
        );
      case ApprovalStatus.timeout:
        return ApprovalResult.timeout(
          'Approval timed out',
          totalLatency,
          name,
          stages,
        );
      case ApprovalStatus.unavailable:
        return ApprovalResult.unavailable(
          'UI unavailable',
          name,
        );
    }
  }
}

